spring:
  profiles:
    active: dev


---
server:
  port: 7001

#spring的配置
spring:
  application:
    name: springcloud-config-eureka
  profiles: dev

#Eureka配置
eureka:
  instance:
    hostname: eureka7001.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false # 是否向eureka注册中心注册自己
    fetch-registry: false # 如果为FALSE 则表示自己为注册中心
    service-url:  #监控页面
      #单机
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      #集群   要与其他的注册中心关联
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

---
server:
  port: 7001

#spring的配置
spring:
  application:
    name: springcloud-config-eureka
  profiles: test

#Eureka配置
eureka:
  instance:
    hostname: eureka7001.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false # 是否向eureka注册中心注册自己
    fetch-registry: false # 如果为FALSE 则表示自己为注册中心
    service-url:  #监控页面
      #单机
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      #集群   要与其他的注册中心关联
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka


