spring:
  profiles:
    active: dev


---
server:
  port: 8001

#mybatis的配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml


#spring的配置
spring:
  profiles: dev
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    username: root
    password: 19981007

#Eureka 注册服务
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka,http://eureka7001.com:7001/eureka
  instance:
    instance-id: springcloud-provider-dept8001 # 修改默认描述信息
info:
  app.name: chen-springcloud

---
server:
  port: 8001

#mybatis的配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml


#spring的配置
spring:
  profiles: test
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    username: root
    password: 19981007

#Eureka 注册服务
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka,http://eureka7001.com:7001/eureka
  instance:
    instance-id: springcloud-provider-dept8001 # 修改默认描述信息
info:
  app.name: chen-springcloud

