spring
  profiles:
    active: dev
---
server
  port: 8201
#spring的配置
spring:
  application:
    name: springcloud-provider-dept
  profiles: dev


#Eureka 注册服务
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka,http://eureka7001.com:7001/eureka

---
server
  port: 8202
#spring的配置
spring:
  application:
    name: springcloud-provider-dept
  profiles: test


#Eureka 注册服务
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka,http://eureka7001.com:7001/eureka
